spring:
  datasource:
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: root
    password: pass
  jpa:
    show-sql: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      #use-new-id-generator-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: metrics